import {stages,referenceInputs} from '../src/stages.ts';
import {buildChain,replay,saveState} from '../src/engine.ts';
const status=document.querySelector('#status')!,report=document.querySelector('#report')!,iframe=document.querySelector<HTMLIFrameElement>('#game')!;
const run=document.querySelector<HTMLButtonElement>('#run')!,download=document.querySelector<HTMLButtonElement>('#export')!;
const touchMode=new URLSearchParams(location.search).has('touch');
if(touchMode){iframe.style.width='390px';iframe.style.height='680px';document.querySelector('h1')!.textContent='80레벨 모바일 터치 검사';document.querySelector('h1+p')!.textContent='프로덕션 번들 · 390px 화면 · 터치 PointerEvent · 제어된 게임 시계';}
const viewport=document.querySelector<HTMLSelectElement>('#viewport')!;viewport.onchange=()=>{const [width,height]=viewport.value.split('x');iframe.style.width=width+'px';iframe.style.height=height+'px';};document.querySelector<HTMLButtonElement>('#preview')!.onclick=()=>mount(document.querySelector<HTMLSelectElement>('#preview-stage')!.value);
const results:unknown[]=[],errors:string[]=[];let w:any;
const flush=()=>new Promise<void>(resolve=>{const channel=new MessageChannel();channel.port1.onmessage=()=>{channel.port1.close();channel.port2.close();resolve()};channel.port2.postMessage(null)});
async function settle(){await flush();await flush();await flush()}
function assert(value:unknown,label:string){if(!value)throw new Error(label)}
async function frame(ms=100){w.qaFrame(ms);await settle()}
function area(){return w.document.querySelector('[role=application]')}
async function key(k:string,target=area(),repeat=false){target.dispatchEvent(new w.KeyboardEvent('keydown',{key:k,repeat,bubbles:true,cancelable:true}));target.dispatchEvent(new w.KeyboardEvent('keyup',{key:k,bubbles:true,cancelable:true}));await settle()}
async function click(label:string,scope=w.document){const b=Array.from(scope.querySelectorAll('button')).find((b:any)=>b.textContent.includes(label)) as HTMLButtonElement;assert(b&&!b.disabled,'missing/enabled '+label);b.click();await settle();await frame(0)}
async function move(m:string){if(m!=='.'){
 if(touchMode){const button=w.document.querySelector(`.direction-pad button[aria-label="${({U:'위',D:'아래',L:'왼쪽',R:'오른쪽'} as Record<string,string>)[m]}"]`);assert(button&&!button.disabled,'touch direction');for(const type of ['pointerdown','pointerup'])button.dispatchEvent(new w.PointerEvent(type,{pointerId:1,pointerType:'touch',button:0,bubbles:true,cancelable:true}));await settle()}
 else await key(({U:'ArrowUp',D:'ArrowDown',L:'ArrowLeft',R:'ArrowRight'} as Record<string,string>)[m]);
 }else if(w.document.querySelector('.live-label').textContent.includes('일시정지')){touchMode?await click('계속',w.document.querySelector('.game-controls')):await key(' ')}await frame()}

function readDB(key:string):Promise<any>{return new Promise((resolve,reject)=>{const req=indexedDB.open('echoloop-browser-qa-v1',1);req.onsuccess=()=>{const d=req.result,t=d.transaction('data','readonly'),r=t.objectStore('data').get(key);t.oncomplete=()=>{d.close();resolve(r.result)};t.onerror=()=>reject(t.error)}})}
async function mount(stage:string){iframe.src='/qa-frame.html?stage='+encodeURIComponent(stage);await new Promise<void>(resolve=>iframe.onload=()=>resolve());w=iframe.contentWindow;w.addEventListener('error',(e:ErrorEvent)=>errors.push(e.message));for(let i=0;i<200&&!area();i++)await new Promise(r=>setTimeout(r,10));assert(area(),'app mounted');await frame(0)}
run.onclick=async()=>{run.disabled=true;document.querySelector<HTMLButtonElement>('#preview')!.disabled=true;results.length=0;errors.length=0;const began=new Date().toISOString();try{
 await new Promise<void>((resolve,reject)=>{const r=indexedDB.deleteDatabase('echoloop-browser-qa-v1');r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)});
 await mount(stages[0].id);
 for(let n=0;n<stages.length;n++){const stage=stages[n],loops=referenceInputs[n];status.textContent=`진행 ${n+1}/80 · ${stage.title}`;assert(w.location.pathname==='/play/'+stage.id,'correct level '+stage.id);
  for(let l=0;l<loops.length;l++){for(let t=0;t<loops[l].length;t++){await move(loops[l][t]);if(t===Math.floor(loops[l].length/2)&&l===loops.length-1&&n%10===0){touchMode?await click('일시정지',w.document.querySelector('.game-controls')):await key(' ');await frame(0);const saved=await readDB('save');assert(saved?.stage.id===stage.id,'persist stage');const pos=w.document.querySelector('.player').getAttribute('transform');await mount(stage.id);assert(w.document.querySelector('.player').getAttribute('transform')===pos,'reload position')}}if(l<loops.length-1){touchMode?await click('기록 확정',w.document.querySelector('.game-controls')):await key('Enter');await frame(0);assert(w.document.querySelectorAll('.record').length===l+1,'committed record '+stage.id)}}
  let result=w.document.querySelector('.result');assert(result?.textContent.includes('우리는, 해냈습니다'),'victory '+stage.id);assert(parseInt(w.document.querySelector('.moves-stat b').textContent)===4,'four spare moves remain '+stage.id);assert(w.document.activeElement===result.querySelector('button'),'default next focus');
  if(n%10===0){await click('한 수 되돌리기',result);assert(!w.document.querySelector('.result'),'undo closes victory');await move(loops.at(-1)!.at(-1)!);assert(w.document.querySelector('.result'),'reclear after undo');result=w.document.querySelector('.result')}
  if(touchMode){await click(n<stages.length-1?'다음 실험':'실험 목록으로',result)}else{
   await key('Enter',result.querySelector('button'),true);assert(w.document.querySelector('.result'),'repeated Enter ignored');
   // Enter must advance even if the user previously tabbed onto Undo.
   const undo=Array.from(result.querySelectorAll('button')).find((b:any)=>b.textContent.includes('한 수 되돌리기')) as HTMLButtonElement;undo.focus();await key('Enter',undo);await frame(0);
  }
  results.push({level:n+1,id:stage.id,status:'passed',moveLimit:stage.moveLimit,movesRemaining:4,loops:loops.map(v=>v.length)});report.textContent=JSON.stringify({passed:results.length,last:results.at(-1)},null,2);
 }
 assert(w.location.pathname==='/','final return home');assert(w.document.querySelector('.completion').textContent.includes('80 / 80'),'all completed UI');let persisted=await readDB('completed');for(let attempt=0;attempt<40&&persisted?.length!==80;attempt++){await new Promise(r=>setTimeout(r,50));persisted=await readDB('completed')}assert(persisted?.length===80,'all completion persisted: '+persisted?.length);assert(!errors.length,'browser errors');
 const result={kind:touchMode?'Chromium at 390px with DOM touch pointer input and controlled animation clock':'Chromium production bundle with DOM keyboard input and controlled animation clock',began,finished:new Date().toISOString(),levels:80,checks:['80 sequential victories','four spare moves per complete solution','all record commits',...(touchMode?['touch directions and on-screen record/next buttons']:['result Enter advance even from Undo focus','held Enter ignored']),'sampled reload and rewind','persisted 80 completions'],results,errors};report.textContent=JSON.stringify(result,null,2);status.textContent=touchMode?'통과: 모바일 터치 80 / 80 · 기록 버튼 · 다음 레벨 · 되돌리기 · 저장 복구':'통과: 80 / 80 · 기록 확정 · 결과창 Enter · 되돌리기 · 저장 복구';download.disabled=false;document.querySelector<HTMLButtonElement>('#preview')!.disabled=false;download.onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));a.download='campaign-browser.json';a.click()};if(touchMode)await mount(stages[2].id);
 }catch(e){status.textContent='실패: '+(e as Error).message;report.textContent=JSON.stringify({passed:results.length,errors,error:String(e)},null,2);run.disabled=false}}

// Geometry needs Chromium: small screens, larger text, and long-map zoom centering.
document.querySelector<HTMLButtonElement>('#layout')!.onclick=async()=>{const checks:unknown[]=[];status.textContent='화면 검사 0/12';report.textContent='';try{
 for(const [width,height,large] of [[320,568,false],[390,680,false],[740,390,false],[320,568,true],[980,800,false],[1366,900,false]] as const){
  iframe.style.width=width+'px';iframe.style.height=height+'px';
  for(const n of [2,49]){await mount(stages[n].id);await click('⚙ 설정',w.document.querySelector('.map-tools'));const checkbox=w.document.querySelector('.setting-row:nth-of-type(3) input');assert(checkbox,'large-text setting');if(checkbox.checked!==large){checkbox.click();await settle()}await key('Escape',w.document.querySelector('[role=dialog]'));await frame(0);
   await new Promise<void>(resolve=>setTimeout(resolve,100));await frame(0);const doc=w.document,dockElement=doc.querySelector('.play-inputs'),dock=dockElement.getBoundingClientRect(),mapElement=doc.querySelector('.game-viewport'),map=mapElement.getBoundingClientRect(),fixed=w.getComputedStyle(dockElement).position==='fixed',board=doc.querySelector('.game-map-inner .board') as SVGSVGElement,boardRect=board.getBoundingClientRect();const targets=Array.from(doc.querySelectorAll('.play-inputs button,.map-tools button')).map((b:any)=>({label:b.getAttribute('aria-label')??b.textContent,rect:b.getBoundingClientRect().toJSON()})).filter(({rect:r})=>r.width&&r.height);
   for(const {label,rect:r} of targets){assert(r.width>=44&&r.height>=44,'44px target '+label);if(fixed)assert(r.left>=0&&r.top>=0&&r.right<=w.innerWidth&&r.bottom<=height,'reachable '+label)}
   assert(map.height>60,'visible map');assert(map.bottom<=dock.top||map.right<=dock.left,'map clear of dock');if(fixed)assert(map.bottom<=height,'mobile map fits first screen');else{const vb=board.viewBox.baseVal;assert(!mapElement.style.getPropertyValue('--play-available-height'),'desktop has no mobile height cap');assert(Math.abs(boardRect.width-(mapElement.clientWidth-8))<1,'desktop map fills available width');const maximum=height*0.56,scale=Math.min(boardRect.width/vb.width,maximum/vb.height);assert(Math.abs(parseFloat(w.getComputedStyle(board).maxHeight)-maximum)<1,'desktop keeps generous map height');assert(Math.abs(board.getScreenCTM()!.a-scale)<0.01,'desktop map keeps original tile scale');}
   const checkBanner=()=>{const banner=doc.querySelector('.pause-banner').getBoundingClientRect(),message=doc.querySelector('.pause-banner span').getBoundingClientRect(),button=doc.querySelector('.pause-banner button').getBoundingClientRect(),focus=doc.querySelector('.game-focus').getBoundingClientRect();assert(Math.abs((message.left+button.right)/2-(banner.left+banner.right)/2)<1,'centered message and action');assert(Math.abs((message.top+message.bottom)/2-(button.top+button.bottom)/2)<1,'vertical alignment');assert(message.left>=banner.left&&button.right<=banner.right,'banner content fits');assert(banner.top>=focus.top-1&&banner.bottom<=focus.bottom+1,'banner fits map');return banner.toJSON()};
   for(const counter of Array.from(doc.querySelectorAll('.game-stats>div')) as HTMLElement[]){const box=counter.getBoundingClientRect(),value=counter.querySelector('b')!.getBoundingClientRect();assert(value.left>=box.left-1&&value.right<=box.right+1,'counter fits its column');}const initialBanner=checkBanner();const tools=Array.from(doc.querySelectorAll('.map-tools button')).map((b:any)=>b.getBoundingClientRect().width);if(width<=760)assert(Math.max(...tools)-Math.min(...tools)<1,'equal toolbar widths');
   if(width>760){const buttons=Array.from(doc.querySelectorAll('.game-controls button')).map((b:any)=>b.getBoundingClientRect()),sizes=buttons.map((b:any)=>b.width);assert(Math.max(...sizes)-Math.min(...sizes)<1,'equal desktop action widths');for(const top of new Set(buttons.map((b:any)=>b.top))){const row=buttons.filter((b:any)=>b.top===top);assert(Math.abs((row[0].left+row.at(-1).right)/2-(dock.left+dock.right)/2)<1,'centered action row')}}
   if(doc.querySelector('.pause-banner button').textContent.includes('시작하기'))await click('시작하기',doc.querySelector('.pause-banner'));else await click('계속하기',doc.querySelector('.pause-banner'));await frame(100);await key(' ');await frame(0);const pausedBanner=checkBanner();
   await click('⊕ 확대',doc.querySelector('.map-tools'));await frame(0);const p=doc.querySelector('.player').getBoundingClientRect(),box=doc.querySelector('.game-viewport').getBoundingClientRect();assert(p.right>box.left&&p.left<box.right&&p.bottom>box.top&&p.top<box.bottom,'zoom keeps player in view');
   await click('⊖ 전체 지도',doc.querySelector('.map-tools'));assert(doc.querySelector('.game-viewport').scrollLeft===0&&doc.querySelector('.game-viewport').scrollTop===0,'full map resets pan');
   checks.push({viewport:width+'x'+height,stage:stages[n].id,large,targets,map:map.toJSON(),board:boardRect.toJSON(),renderedMap:{width:board.viewBox.baseVal.width*board.getScreenCTM()!.a,height:board.viewBox.baseVal.height*board.getScreenCTM()!.d},fixedDock:fixed,dock:dock.toJSON(),zoomPlayerVisible:true,initialBanner,pausedBanner,centeredBanner:true,equalToolbar:width<=760});status.textContent=`화면 검사 ${checks.length}/12`;
  }
 }
 iframe.style.width='390px';iframe.style.height='680px';await mount(stages[2].id);await click('⚙ 설정',w.document.querySelector('.map-tools'));const larger=w.document.querySelector('.setting-row:nth-of-type(3) input');if(larger.checked){larger.click();await settle()}await key('Escape',w.document.querySelector('[role=dialog]'));await frame(0);
 for(const m of referenceInputs[2][0])await move(m);await click('기록 확정',w.document.querySelector('.game-controls'));await move('R');await click('반복 재시작',w.document.querySelector('.game-controls'));
 assert(w.document.querySelector('[aria-label="재시작 취소"]'),'recovery button visible');report.textContent=JSON.stringify({kind:'Chromium viewport and user-journey checks',checks,errors},null,2);status.textContent='통과: 화면 12개 · PC 지도 원래 크기 · 모바일 겹침 없음 · 중앙 정렬 · 44px 조작';
 }catch(e){status.textContent='실패: '+(e as Error).message;report.textContent=JSON.stringify({checks,error:String(e)},null,2)}};

// Reproduce the reported door-opening trigger in Chromium, then exercise budget recovery.
async function seedSave(value:unknown){await new Promise<void>((resolve,reject)=>{
 const req=indexedDB.open('echoloop-browser-qa-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('data');
 req.onsuccess=()=>{const db=req.result,tx=db.transaction('data','readwrite');tx.objectStore('data').put(value,'save');tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>reject(tx.error)};
});}
document.querySelector<HTMLButtonElement>('#budget-input')!.onclick=async()=>{const checks:unknown[]=[];status.textContent='문 앞 입력·이동 제한 검사 중';report.textContent='';try{
 iframe.style.width='390px';iframe.style.height='680px';
 const position=()=>w.document.querySelector('.player').getAttribute('transform'),remaining=()=>parseInt(w.document.querySelector('.moves-stat b').textContent);
 for(const mode of ['keyboard','touch']){
  const m=stages[2],ghosts=buildChain(m,[[...Array(20).fill('.'),'U','U','R']]);await seedSave(saveState(m,replay(m,['R','R'],ghosts)));await mount(m.id);
  const before=position(),moves=remaining();
  const press=(type:string,repeat=false)=>{if(mode==='keyboard')area().dispatchEvent(new w.KeyboardEvent(type==='down'?'keydown':'keyup',{key:'ArrowRight',repeat,bubbles:true,cancelable:true}));else w.document.querySelector('.direction-pad button[aria-label="오른쪽"]').dispatchEvent(new w.PointerEvent(type==='down'?'pointerdown':'pointerup',{pointerId:1,pointerType:'touch',button:0,bubbles:true,cancelable:true}));};
  press('down');await settle();await frame(100);assert(position()===before,'initial closed door blocks movement');
  for(let i=0;i<25;i++){if(mode==='keyboard')press('down',true);await frame(100)}
  assert(w.document.querySelector('path[fill="#8163a422"]'),'echo opens door A');assert(position()===before,'held blocked direction stays stopped after opening');assert(remaining()===moves,'waiting and blocked input cost no moves');
  press('up');press('down');press('up');await settle();await frame(100);const after=position();assert(after!==before,'fresh press enters open door');await frame(300);assert(position()===after,'fresh tap moves only once');assert(remaining()===moves-1,'fresh move costs once');
  checks.push({mode,closedDoorHeld:true,openedWithoutDrift:true,freshTapOneMove:true,remaining:remaining()});
 }
 const m=stages[0],s=replay(m,['U','D','U','D','U','D','U','D','R']);await seedSave(saveState(m,s));await mount(m.id);await move('R');const loss=w.document.querySelector('.result');assert(loss?.textContent.includes('이동 횟수를 모두 사용했습니다'),'move exhaustion dialog');assert(remaining()===0,'zero remaining');assert(w.document.activeElement===loss.querySelector('button'),'loss focuses Undo');
 await key('z',loss);await frame(0);assert(!w.document.querySelector('.result')&&remaining()===1,'Z restores remaining move');await key('r');await frame(0);assert(remaining()===10,'restart restores current loop budget');await key('z');await frame(0);assert(remaining()===1,'restart recovery restores prior counter');checks.push({moveExhaustion:true,undo:true,restart:true,restartRecovery:true});
 await seedSave(saveState(m,replay(m,['U','D','U','D'])));await mount(m.id);for(let i=0;i<6;i++)await move('R');assert(w.document.querySelector('.result')?.textContent.includes('우리는, 해냈습니다'),'two mistakes still win');assert(remaining()===0,'last permitted move wins');checks.push({twoMistakesWin:true,lastMoveWins:true});
 report.textContent=JSON.stringify({kind:'Chromium production bundle blocked-input and move-budget journeys',checks,errors},null,2);status.textContent='통과: 키보드·터치 문 앞 입력 · 이동 소진 · Z·재시작 복구 · 마지막 이동 성공';
 }catch(e){status.textContent='실패: '+(e as Error).message;report.textContent=JSON.stringify({checks,error:String(e)},null,2)}};
