import {type Stage,type State,type Cell,equal} from './engine.ts';
export const colors=['#e2a062','#bcb387','#c69782'];
export function Board({stage:m,state:s,paths=false,onCell,selected,connections=false,large=false}:{stage:Stage;state?:State;paths?:boolean;onCell?:(c:Cell)=>void;selected?:Cell;connections?:boolean;large?:boolean}){
 const z=48;return <svg className={'board '+(large?'large':'')} viewBox={`0 0 ${m.width*z} ${m.height*z}`} role={onCell?'group':'img'} aria-label={onCell?'맵 편집 격자':'퍼즐 지도. 흰색 원은 현재 나, 번호가 있는 원은 과거의 나입니다.'}>
 <defs><filter id="glow"><feGaussianBlur stdDeviation="3"/></filter><pattern id="grid" width="48" height="48" patternUnits="userSpaceOnUse"><path d="M48 0H0V48" fill="none" stroke="#424b3c" strokeWidth=".8"/></pattern></defs>
 <rect width={m.width*z} height={m.height*z} rx="1" fill="#242c24"/>
 <rect width={m.width*z} height={m.height*z} fill="url(#grid)"/>
 {m.tiles.map((wall,i)=>wall?<g key={i}><rect x={i%m.width*z+2} y={Math.floor(i/m.width)*z+2} width="44" height="44" rx="1" fill="#3a4233"/><path d={`M${i%m.width*z+8} ${Math.floor(i/m.width)*z+8}h32`} stroke="#535e46" strokeWidth="2"/></g>:null)}
 {connections&&m.doors.flatMap(d=>d.plateIds.map(id=>{const p=m.plates.find(p=>p.id===id);return p?<path key={d.id+id} d={`M${p.x*z+24} ${p.y*z+24}L${d.x*z+24} ${d.y*z+24}`} stroke="#f7ca82" strokeWidth="2" strokeDasharray="5 5" opacity=".5"/>:null;}))}
 <rect x={m.spawn.x*z+9} y={m.spawn.y*z+9} width="30" height="30" rx="7" fill="none" stroke="#67849a" strokeDasharray="4 4"/>
 <text x={m.spawn.x*z+24} y={m.spawn.y*z+29} textAnchor="middle" fill="#7795aa" fontSize="13">S</text>
 <g transform={`translate(${m.goal.x*z},${m.goal.y*z})`}><rect x="5" y="5" width="38" height="38" rx="2" fill="#93d5dc" opacity=".12"/><rect x="10" y="10" width="28" height="28" rx="5" fill="none" stroke="#93d5dc" strokeWidth="2"/><path d="M17 24h14m-6-6 6 6-6 6" fill="none" stroke="#93d5dc" strokeWidth="2.5"/></g>
 {m.plates.map((p,i)=><g key={p.id} transform={`translate(${p.x*z},${p.y*z})`}><rect x="8" y="8" width="32" height="32" rx="8" fill={s?.plates[p.id]?'#d6b878':'#49462e'} stroke="#d6b878" strokeWidth="2"/><text x="24" y="29" textAnchor="middle" fill={s?.plates[p.id]?'#202330':'#d6b878'} fontSize="15" fontWeight="700">{String.fromCharCode(65+i)}</text></g>)}
 {m.doors.map((d,i)=><g key={d.id} transform={`translate(${d.x*z},${d.y*z})`}><rect x="3" y="3" width="42" height="42" rx="4" fill={s?.doors[d.id]?'#2d4c46':'#443e33'} stroke={s?.doors[d.id]?'#93d5dc':'#bc9976'} strokeWidth="2" opacity={s?.doors[d.id]?.valueOf()?0.6:1}/>{!s?.doors[d.id]&&[14,24,34].map(x=><path key={x} d={`M${x} 9v30`} stroke="#bc9976" strokeWidth="3"/>)}<text x="24" y="-4" textAnchor="middle" fill="#afbabf" fontSize="10">{d.mode==='AND'?'AND':String.fromCharCode(65+i)}</text></g>)}
 {paths&&s?.ghosts.map((g,i)=><polyline key={'path'+i} points={g.cells.slice(0,g.originalTicks+1).map(c=>`${c.x*z+24},${c.y*z+24}`).join(' ')} fill="none" stroke={colors[i]} strokeWidth="2" strokeDasharray="4 5" opacity=".42"/>)}
 {s?.ghosts.map((g,i)=><g key={"echo-trail"+i} aria-hidden="true">{[6,4,2].filter(t=>s.tick>=t).map(t=>{const c=g.cells[s.tick-t];return <circle key={t} cx={c.x*z+24} cy={c.y*z+24} r={9-t/2} fill={colors[i]} opacity={.2-t*.02}/>;})}</g>)}
 {s?.ghosts.map((g,i)=>{const p=g.cells[s.tick],overlap=s.ghosts.slice(0,i).filter(v=>equal(v.cells[s.tick],p)).length;return <g key={i} transform={`translate(${p.x*z+24+overlap*7},${p.y*z+24-7*overlap})`}><circle r="16" fill={colors[i]} opacity=".17"/><circle r="14" fill="#282d22" stroke={colors[i]} strokeWidth="2" strokeDasharray="3 2"/><text y="5" textAnchor="middle" fill={colors[i]} fontSize="15" fontWeight="700">{i+1}</text></g>;})}
 {s&&<g className="player" transform={`translate(${s.current.x*z+24},${s.current.y*z+24})`}><circle r="20" fill="#a5dde2" opacity=".2" filter="url(#glow)"/><circle r="12" fill="#eef4e8" stroke="#93d5dc" strokeWidth="3"/><circle cx="-3" cy="-2" r="1.5" fill="#21352e"/><circle cx="4" cy="-2" r="1.5" fill="#21352e"/></g>}
 {onCell&&m.tiles.map((_,i)=><rect key={'hit'+i} role="button" aria-label={`${i%m.width},${Math.floor(i/m.width)} 셀`} tabIndex={0} x={i%m.width*z} y={Math.floor(i/m.width)*z} width={z} height={z} fill="transparent" className="cell-hit" onClick={()=>onCell({x:i%m.width,y:Math.floor(i/m.width)})} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onCell({x:i%m.width,y:Math.floor(i/m.width)});}}}/>)}
 {selected&&<rect x={selected.x*z+1} y={selected.y*z+1} width="46" height="46" fill="none" stroke="#fff" strokeWidth="2" pointerEvents="none"/>}
 </svg>;
}
