import {useId} from 'react';
import {type Stage,type State,type Cell,equal,echoPositions,frozenEcho} from './engine.ts';
import {Traveler,echoColors} from './Traveler.tsx';
export const colors=echoColors;
export function Board({stage:m,state:s,paths=false,onCell,selected,connections=false,large=false}:{stage:Stage;state?:State;paths?:boolean;onCell?:(c:Cell)=>void;selected?:Cell;connections?:boolean;large?:boolean}){
 const z=48,id=useId().replaceAll(':',''),floor=`floor-${id}`;
 return <svg className={'board '+(large?'large':'')} viewBox={`0 0 ${m.width*z} ${m.height*z}`} role={onCell?'group':'img'} aria-label={onCell?'맵 편집 격자':'퍼즐 지도. 금빛 후드 여행자는 현재, 번호가 있는 유령은 과거입니다.'}>
 <defs><linearGradient id={floor} x2="0" y2="1"><stop stopColor="#2b2444"/><stop offset="1" stopColor="#1c1930"/></linearGradient></defs>
 {m.tiles.map((wall,i)=>{const x=i%m.width*z,y=Math.floor(i/m.width)*z;return wall?<g key={i}><path d={`M${x+7} ${y+4}h30l7 7v28l-7 6H${x+7}Z`} fill="#0f0d20"/><path d={`M${x+9} ${y+7}h27l5 5`} fill="none" stroke="#413354" strokeWidth="1"/><path d={`M${x+13} ${y+20}l10-7 12 10-11 12Z`} fill="#1d182d" opacity={.3+(i%4)*.13}/></g>:<g key={i}><rect x={x+1} y={y+1} width="46" height="46" rx="4" fill={`url(#${floor})`} stroke="#6c53812e"/><circle cx={x+24} cy={y+24} r="1" fill="#b39dc1" opacity=".2"/></g>;})}
 {m.fragile?.map((p,i)=><g className={s?.broken?.includes(i)?'collapsed-tile':'fragile-tile'} key={'fragile'+i} transform={`translate(${p.x*z+24},${p.y*z+24})`}><rect x="-22" y="-22" width="44" height="44" rx="4" fill={s?.broken?.includes(i)?'#07060d':'#75435733'} stroke="#e2a0b5" strokeDasharray="4 3"/>{s?.broken?.includes(i)?<path d="m-18-15 8 4 5-6 12 4 9-3m-34 34 7-6 7 5 9-7 9 7" stroke="#c7869e" fill="none"/>:<path d="m-13-18 7 12-7 9 15 5-2 13m-6-27 16-8m-8 22 16-9" stroke="#efb0c4" strokeWidth="2" fill="none"/>}</g>)}
 {m.stasis?.map((p,i)=><g className="stasis-pad" key={'stasis'+i} transform={`translate(${p.x*z+24},${p.y*z+24})`}><rect x="-18" y="-18" width="36" height="36" rx="9" fill={s&&equal(p,s.current)?'#8fe4ec55':'#153744'} stroke="#8fe4ec" strokeWidth="2"/><text textAnchor="middle" y="5" fill="#c0f8ff" fontSize="15" fontWeight="700">Ⅱ {p.ghost}</text></g>)}
 {connections&&m.doors.flatMap(d=>d.plateIds.map(pid=>{const p=m.plates.find(p=>p.id===pid);return p?<path key={d.id+pid} d={`M${p.x*z+24} ${p.y*z+24}L${d.x*z+24} ${d.y*z+24}`} stroke="#f7ca82" strokeWidth="2" strokeDasharray="5 5" opacity=".5"/>:null;}))}
 <g transform={`translate(${m.spawn.x*z+24},${m.spawn.y*z+24})`} fill="none" stroke="#9c8bac" opacity=".6"><circle r="16" strokeDasharray="2 5"/><path d="M-6 4 0-6 6 4Z"/></g>
 <g className="exit-rift" transform={`translate(${m.goal.x*z+24},${m.goal.y*z+24})`}><ellipse rx="15" ry="19" fill="#ceafff" opacity=".15"/><path d="m0-20-10 12 6 8-5 15L4 4 1-4 10-17 2-11Z" fill="#f8d5ff"/><ellipse rx="18" ry="21" fill="none" stroke="#c599f0" strokeWidth="1.5" strokeDasharray="7 5"/></g>
 {!!m.shards?.length&&<text x={m.goal.x*z+24} y={m.goal.y*z+52} textAnchor="middle" fill="#ffdd91" fontSize="10">{s?.collected?.length??0}/{m.shards.length}</text>}
 {m.shards?.map((p,i)=><g key={'shard'+i} transform={`translate(${p.x*z+24},${p.y*z+24})`} opacity={s?.collected?.includes(i)?.18:1}><path d="M0-15 10-3 0 15-10 3Z" fill="#83eadb" stroke="#e2fff9" strokeWidth="2"/>{s?.collected?.includes(i)&&<path d="m-7 0 5 5 10-11" stroke="#fff" fill="none" strokeWidth="2"/>}</g>)}
 {m.portals?.flatMap((p,i)=>[p.a,p.b].map((c,j)=><g key={p.id+j} transform={`translate(${c.x*z+24},${c.y*z+24})`}><circle r="17" fill="#5d42a3" fillOpacity=".4" stroke="#b49aff" strokeWidth="2"/><ellipse rx="11" ry="17" fill="none" stroke="#d9c5ff" transform={`rotate(${j?45:-45})`}/><text textAnchor="middle" y="5" fill="#fff" fontSize="13" fontWeight="700">{i+1}</text></g>))}
 {m.arrows?.map((a,i)=><g key={'arrow'+i} transform={`translate(${a.x*z+24},${a.y*z+24}) rotate(${{U:-90,R:0,D:90,L:180}[a.direction]})`}><path d="M-17-15H5L19 0 5 15h-22" fill="#285264" opacity=".5"/><path d="m-9-10 10 10-10 10m10-20 10 10-10 10" fill="none" stroke="#8fd1f3" strokeWidth="2"/></g>)}
 {m.plates.map((p,i)=>{const active=s?.plates[p.id],color=p.kind==='charge'?'#f8d66d':p.kind==='solo'?'#a3d6ff':p.kind==='resonance'?'#ffbd91':p.kind==='toggle'?'#a9e5df':p.kind==='echo'?'#d798ff':p.kind==='present'?'#ffe1a3':'#b7c2f0';return <g key={p.id} transform={`translate(${p.x*z+24},${p.y*z+24})`}><path d="M0-19 19 0 0 19-19 0Z" fill={active?color:'#29233f'} fillOpacity={active?0.35:1} stroke={color} strokeWidth="2" strokeDasharray={p.kind==='echo'?'3 2':undefined}/><text y="5" textAnchor="middle" fill={color} fontSize="14" fontWeight="700">{String.fromCharCode(65+i)}</text>{p.kind&&p.kind!=='weight'&&<text y="-23" textAnchor="middle" fill={color} fontSize="10">{p.kind==='charge'?'◴':p.kind==='solo'?'1×':p.kind==='resonance'?`${p.minActors??2}×`:p.kind==='toggle'?'↺':p.kind==='echo'?'◇':'✦'}</text>}{p.kind==='charge'&&<><rect x="-18" y="23" width="36" height="4" fill="#514427"/><rect x="-18" y="23" width={36*(s?.charges?.[p.id]??0)/(p.chargeTicks??10)} height="4" fill={color}/><text y="37" textAnchor="middle" fill={color} fontSize="8">{((p.chargeTicks??10)/10).toFixed(1)}s</text></>}{p.kind==='toggle'&&<text y="32" textAnchor="middle" fill={color} fontSize="8">{active?'ON':'OFF'}</text>}{p.kind==='resonance'&&<><circle cx="-7" cy="22" r="3" fill="none" stroke={color}/><circle cx="0" cy="22" r="3" fill="none" stroke={color}/>{p.minActors===3&&<circle cx="7" cy="22" r="3" fill="none" stroke={color}/>}</>}</g>;})}
 {m.doors.map(d=>{const open=s?.doors[d.id],phase=d.pulse?((s?.tick??0)+d.pulse.offset)%d.pulse.period/d.pulse.period:0;return <g key={d.id} transform={`translate(${d.x*z+24},${d.y*z+24})`}><path d="M-20-21h40v42h-40Z" fill={open?'#8163a422':'#513657'} stroke={open?'#b19dde':'#f096bc'} strokeWidth="1.5"/>{d.inverted&&<text x="14" y="18" fill="#ffcf9e" fontWeight="700" fontSize="12">!</text>}{!open&&<path d="m-15-17 30 34m-30 0 30-34M0-18v36" stroke="#f7a1cf" strokeWidth="2"/>}<text x="0" y="-24" textAnchor="middle" fill="#e6c9ed" fontSize="10">{d.inverted?'! ':''}{d.plateIds.map(pid=>String.fromCharCode(65+m.plates.findIndex(p=>p.id===pid))).join(d.mode==='AND'?'&':'/')}</text>{d.pulse&&<><circle r="14" fill="#171224" stroke="#5a455f" strokeWidth="3"/><circle r="14" fill="none" stroke="#ffd399" strokeWidth="3" strokeDasharray={`${88*phase} 88`} transform="rotate(-90)"/><text y="4" textAnchor="middle" fill="#ffe1ac" fontSize="10">◷</text></>}</g>;})}
 {paths&&s?.ghosts.map((g,i)=><path key={'path'+i} d={g.cells.slice(0,g.originalTicks+1).map((c,j)=>`${!j||Math.abs(c.x-g.cells[j-1].x)+Math.abs(c.y-g.cells[j-1].y)>1?'M':'L'}${c.x*z+24},${c.y*z+24}`).join(' ')} fill="none" stroke={colors[i]} strokeWidth="2" strokeDasharray="3 5" opacity=".45"/>)}
 {(s?.crates??m.crates)?.map((p,i)=><g className="time-crate" data-cell={`${p.x},${p.y}`} key={'crate'+i} transform={`translate(${p.x*z+24},${p.y*z+24})`}><rect x="-17" y="-17" width="34" height="34" rx="4" fill="#624720" stroke="#f2cf7b" strokeWidth="2"/><path d="M-12-12h24v24h-24Zm0 0 24 24m0-24-24 24" stroke="#e6b957" strokeWidth="1.5" fill="none"/>{m.plates.some(a=>equal(a,p))&&<text y="31" textAnchor="middle" fill="#ffe1a3" fontSize="11">{String.fromCharCode(65+m.plates.findIndex(a=>equal(a,p)))}</text>}</g>)}
 {s&&echoPositions(m,s).map((p,i)=>{const overlap=echoPositions(m,s).slice(0,i).filter(v=>equal(v,p)).length;return <g className={'echo-position'+(frozenEcho(m,s,i)?' is-frozen':'')} key={i} transform={`translate(${p.x*z+24+overlap*7},${p.y*z+24-7*overlap})`}><Traveler echo index={i}/>{frozenEcho(m,s,i)&&<><circle r="22" fill="none" stroke="#8fe4ec" strokeWidth="2" strokeDasharray="4 3"/><text x="14" y="-16" fontSize="12" fill="#c0f8ff">Ⅱ</text></>}{m.echoMode==='reverse'&&<text x="-20" y="-16" fontSize="15" fill="#c0f8ff">↶</text>}</g>;})}
 {s&&<g className="player" transform={`translate(${s.current.x*z+24},${s.current.y*z+24})`}><Traveler/></g>}
 {onCell&&m.tiles.map((_,i)=><rect key={'hit'+i} role="button" aria-label={`${i%m.width},${Math.floor(i/m.width)} 셀`} tabIndex={0} x={i%m.width*z} y={Math.floor(i/m.width)*z} width={z} height={z} fill="transparent" className="cell-hit" onClick={()=>onCell({x:i%m.width,y:Math.floor(i/m.width)})} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onCell({x:i%m.width,y:Math.floor(i/m.width)});}}}/>)}
 {selected&&<rect x={selected.x*z+1} y={selected.y*z+1} width="46" height="46" fill="none" stroke="#fff" strokeWidth="2" pointerEvents="none"/>}
 </svg>;
}
