import React,{useState,useRef,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Board,colors} from './Board.tsx';
import {Studio} from './Studio.tsx';
import {stages} from './stages.ts';
import {type Stage,type State,type Move,type Solution,initial,step,commit,saveState,restoreState,solution,verifySolution,hash,inputDirection,frameTicks} from './engine.ts';
import {read,write,download,parseFile} from './storage.ts';
import './style.css';
type Settings={paths:boolean;motion:boolean;large:boolean;sound:boolean};
const keyMove:Record<string,Move>={ArrowUp:'U',ArrowDown:'D',ArrowLeft:'L',ArrowRight:'R',w:'U',s:'D',a:'L',d:'R'};
function App(){
 const [view,setView]=useState<'home'|'play'|'studio'>('home'),[stage,setStage]=useState(stages[0]),[state,setState]=useState(()=>initial(stages[0])),[paused,setPaused]=useState(true),[started,setStarted]=useState(false),[test,setTest]=useState(false),[studioResult,setStudioResult]=useState<{stage:Stage;solution:Solution}|null>(null);
 const [toast,setToast]=useState(''),[saved,setSaved]=useState('아직 저장 전'),[resume,setResume]=useState<unknown>(),[completed,setCompleted]=useState<string[]>([]),[myMaps,setMyMaps]=useState<Stage[]>([]),[hint,setHint]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[settings,setSettings]=useState<Settings>({paths:true,motion:true,large:false,sound:false}),[help,setHelp]=useState(false),[deleteIndex,setDeleteIndex]=useState<number|null>(null),[cloud,setCloud]=useState(''),[busy,setBusy]=useState(false);
 const stateRef=useRef(state),stageRef=useRef(stage),pausedRef=useRef(true),held=useRef<Move[]>([]),queued=useRef<Move|null>(null),game=useRef<HTMLDivElement>(null),lastSave=useRef(''),toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null),audio=useRef<AudioContext|null>(null),settingsRef=useRef(settings);
 const notify=(s:string)=>{setToast(s);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),6500);};
 function assign(s:State){stateRef.current=s;setState(s);}
 function pause(p=true){pausedRef.current=p;setPaused(p);held.current=[];queued.current=null;}
 function beep(){if(!settingsRef.current.sound)return;try{audio.current??=new AudioContext();void audio.current.resume();const o=audio.current.createOscillator(),g=audio.current.createGain();o.type='sine';o.frequency.value=660;g.gain.setValueAtTime(.04,audio.current.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.current.currentTime+.12);o.connect(g);g.connect(audio.current.destination);o.start();o.stop(audio.current.currentTime+.12);}catch{}}
 function focus(){requestAnimationFrame(()=>game.current?.focus());}
 function play(m:Stage,isTest=false,s?:State){pause();setStage(m);stageRef.current=m;assign(s??initial(m));setStarted(!!s?.tick);setTest(isTest);setView('play');setHint(false);lastSave.current='';focus();history.replaceState(null,'',`/play/${encodeURIComponent(m.id)}`);}
 function navigate(next:'home'|'studio'){if(view==='play')void persist();pause();setView(next);history.replaceState(null,'',next==='home'?'/':'/studio');if(next==='home'){read<Stage[]>('maps').then(v=>setMyMaps(v??[])).catch(()=>{});read('save').then(setResume).catch(()=>{});}}
 async function persist(){if(test)return;const s=stateRef.current,m=stageRef.current,v=saveState(m,s),key=hash(v.solution);if(lastSave.current===key)return;lastSave.current=key;try{await write('save',v);setSaved('이 기기에 저장됨');setResume(v);}catch{lastSave.current='';setSaved('저장 실패 · 내보내기 필요');}}
 useEffect(()=>{const route=decodeURIComponent(location.pathname.split('/').at(-1)??'');Promise.all([read('save'),read<string[]>('completed'),read<Settings>('settings'),read<Stage[]>('maps')]).then(([r,c,p,m])=>{setResume(r);setCompleted(c??[]);if(p)setSettings(p);setMyMaps(m??[]);if(location.pathname.startsWith('/play/')){const existing=r as ReturnType<typeof saveState>|undefined;if(existing?.stage?.id===route){try{const restored=restoreState(existing);play(restored.stage,false,restored.state);}catch(e){notify((e as Error).message);}}else{const selected=stages.find(v=>v.id===route)??m?.find(v=>v.id===route);if(selected)play(selected);}}}).catch(()=>notify('브라우저 저장소를 사용할 수 없습니다. JSON 내보내기를 이용하세요.'));if(location.pathname.startsWith('/studio'))setView('studio');return()=>{if(toastTimer.current)clearTimeout(toastTimer.current);};},[]);
 useEffect(()=>{settingsRef.current=settings;document.documentElement.dataset.motion=settings.motion?'on':'off';document.documentElement.dataset.large=String(settings.large);},[settings]);
 useEffect(()=>{if(view!=='play')return;const timer=setInterval(()=>void persist(),500);return()=>clearInterval(timer);},[view,test]);
 useEffect(()=>{if(view==='play'&&paused)void persist();},[paused,state.ghosts.length,view]);
 useEffect(()=>{const blur=()=>pause(),hide=()=>{if(document.hidden)pause();};window.addEventListener('blur',blur);document.addEventListener('visibilitychange',hide);return()=>{window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',hide);};},[]);
 useEffect(()=>{if(view!=='play')return;let id=0,last=performance.now(),acc=0;function frame(now:number){const delta=now-last;last=now;if(pausedRef.current||stateRef.current.outcome!=='RUNNING'){acc=0;}else{const t=frameTicks(delta,acc);acc=t.accumulator;if(t.pause){pause();notify('잠시 화면이 멈춰 시간을 일시정지했습니다.');}else{for(let i=0;i<t.ticks;i++){const dir=inputDirection(held.current,queued.current);queued.current=null;const next=step(stageRef.current,stateRef.current,dir);assign(next);if(next.outcome!=='RUNNING'){pause();break;}}}}id=requestAnimationFrame(frame);}id=requestAnimationFrame(frame);return()=>cancelAnimationFrame(id);},[view]);
 useEffect(()=>{if(state.outcome!=='WON')return;beep();const proof=solution(stage,state);try{verifySolution(stage,proof);}catch{return notify('해답 재생 검사에 실패했습니다.');}if(test){setStudioResult({stage,solution:proof});}else{setCompleted(v=>{const next=[...new Set([...v,stage.id])];write('completed',next).catch(()=>notify('완료 기록 저장 실패'));return next;});}},[state.outcome,stage.id]);
 function record(){pause();try{const r=commit(stageRef.current,stateRef.current);assign(initial(stageRef.current,[...stateRef.current.ghosts,r]));setStarted(false);beep();notify(`과거 ${stateRef.current.ghosts.length} 생성 · 마지막 자리에서 기다립니다.`);focus();}catch(e){notify((e as Error).message);}}
 function restart(){pause();assign(initial(stageRef.current,stateRef.current.ghosts));setStarted(false);focus();}
 function down(e:React.KeyboardEvent<HTMLDivElement>){if(e.target instanceof HTMLElement&&['INPUT','TEXTAREA','SELECT','BUTTON','A'].includes(e.target.tagName))return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(keyMove[k]){e.preventDefault();if(stateRef.current.outcome!=='RUNNING')return;if(pausedRef.current){pause(false);setStarted(true);}const move=keyMove[k];if(!held.current.includes(move))held.current.push(move);queued.current=move;}else if(e.key===' '){e.preventDefault();if(!e.repeat&&stateRef.current.outcome==='RUNNING'){pause(!pausedRef.current);setStarted(true);}}else if(e.key==='Enter'){e.preventDefault();if(!e.repeat)record();}else if(k==='r'){e.preventDefault();if(!e.repeat)restart();}}
 function up(e:React.KeyboardEvent<HTMLDivElement>){const k=e.key.length===1?e.key.toLowerCase():e.key;held.current=held.current.filter(v=>v!==keyMove[k]);}
 async function continueGame(){try{const v=restoreState(resume);play(v.stage,false,v.state);}catch(e){notify((e as Error).message);}}
 async function importSave(f?:File){if(!f)return;try{const raw=await parseFile(f),v=restoreState(raw);await write('save',raw);setResume(raw);play(v.stage,false,v.state);notify('저장 기록의 재생 검증 후 복구했습니다.');}catch(e){notify((e as Error).message);}}
 async function cloudSave(){setBusy(true);pause();try{const status=await fetch('/api/status',{signal:AbortSignal.timeout(12000)}).then(r=>r.json());if(!status.database)throw new Error('온라인 저장 연결 준비 중입니다. 현재 진행은 이 기기에 저장됩니다.');let token=await read<string>('cloud-token');if(!token){const bytes=crypto.getRandomValues(new Uint8Array(32));token=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');await write('cloud-token',token);}const revision=await read<number>('cloud-revision')??0;const response=await fetch('/api/backup',{method:'PUT',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({baseRevision:revision,clientMutationId:crypto.randomUUID(),payload:saveState(stageRef.current,stateRef.current)}),signal:AbortSignal.timeout(15000)});const value=await response.json();if(!response.ok)throw new Error(value.error??'온라인 저장에 실패했습니다.');await write('cloud-revision',value.revision);setCloud('온라인 저장 완료');notify('이 브라우저의 온라인 백업을 저장했습니다.');}catch(e){setCloud('온라인 저장 안 됨');notify((e as Error).message);}finally{setBusy(false);}}
 async function cloudRestore(){pause();setBusy(true);try{const token=await read<string>('cloud-token');if(!token)throw new Error('이 브라우저에서 만든 온라인 백업이 없습니다.');const response=await fetch('/api/backup',{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(15000)});const v=await response.json();if(!response.ok)throw new Error(v.error??'백업을 불러오지 못했습니다.');const restored=restoreState(v.payload);if(!confirm('온라인 백업으로 현재 진행을 교체할까요? 현재 기록이 필요하면 먼저 JSON으로 내보내세요.'))return;await write('cloud-revision',v.revision);await write('save',v.payload);play(restored.stage,false,restored.state);notify('온라인 백업을 검증하고 복구했습니다.');}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{if(!(settingsOpen||help||deleteIndex!==null||view==='play'&&state.outcome!=='RUNNING'))return;const dialog=document.querySelector<HTMLElement>('[role=dialog]');const focusables=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea,[tabindex="0"]')??[]);focusables()[0]?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const list=focusables();if(!list.length)return;if(e.shiftKey&&document.activeElement===list[0]){e.preventDefault();list.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===list.at(-1)){e.preventDefault();list[0].focus();}};document.addEventListener('keydown',trap);return()=>document.removeEventListener('keydown',trap);},[settingsOpen,help,deleteIndex,state.outcome,view]);
 const index=stages.findIndex(m=>m.id===stage.id),progress=Math.round(state.tick/300*100);
 return <><header className="header"><button className="brand" onClick={()=>navigate('home')} aria-label="EchoLoop 홈"><span className="brand-mark">↶</span><span>Echo<span className="brand-thin">Loop</span><small>TIME EXPERIMENT / 01</small></span></button><nav><button className={view!=='studio'?'nav-active':''} onClick={()=>navigate('home')}>플레이</button><button className={view==='studio'?'nav-active':''} onClick={()=>navigate('studio')}>맵 제작실</button><button onClick={()=>{pause();setHelp(true);}}>플레이 가이드</button></nav><button className="settings-button" onClick={()=>{pause();setSettingsOpen(true);}} aria-label="설정">⚙ <span>설정</span></button></header>
 {view==='home'&&<main className="home"><div className="home-top"><span className="eyebrow"><i/> TIME LOOP PUZZLE</span><span className="tiny-label">기록은 남고, 가능성은 늘어난다.</span></div><section className="intro"><div className="intro-copy"><h1>혼자서는 닿지 못할 곳.<br/><em>과거의 나와 함께.</em></h1><p>30초의 행동을 남기세요.<br/>어제의 내가 문을 열면, 오늘의 나는 한 걸음 더.</p><div className="intro-actions"><button className="primary" onClick={()=>play(stages[completed.includes(stages[0].id)?Math.min(stages.findIndex(m=>!completed.includes(m.id))<0?0:stages.findIndex(m=>!completed.includes(m.id)),4):0])}>퍼즐 시작하기 <span>↗</span></button>{!!resume&&<button onClick={continueGame}>이어하기 ↶</button>}</div><div className="intro-facts"><span><b>30</b> 초의 반복</span><span><b>3</b> 명의 과거</span><span><b>∞</b> 개의 가능성</span></div></div><div className="preview-map"><div className="preview-caption"><span><i/> EXPERIMENT 04</span><span>두 개의 문, 세 명의 나</span></div><Board stage={stages[3]} state={{...initial(stages[3]),current:{x:8,y:4},plates:{'plate-a':true,'plate-b':true},doors:{'door-a':true,'door-b':true},ghosts:[{cells:Array(301).fill({x:3,y:2}),originalTicks:0,inputPrefix:[],checksum:'',parentChecksum:''},{cells:Array(301).fill({x:7,y:2}),originalTicks:0,inputPrefix:[],checksum:'',parentChecksum:''}]}}/><div className="preview-foot"><span className="dot current"/> 현재의 나 <span className="dot purple"/> 과거 1 <span className="dot orange"/> 과거 2 <span className="preview-note">과거의 발자국은 바뀌지 않는다.</span></div></div></section>
 <section className="chapters"><div className="section-heading"><div><span className="eyebrow">THE FIRST FIVE LOOPS</span><h2>시간을 다루는 다섯 가지 방법</h2></div><span className="completion">{stages.filter(s=>completed.includes(s.id)).length} / 5 완료</span></div><div className="stage-cards">{stages.map((m,i)=><button key={m.id} className={'stage-card '+(completed.includes(m.id)?'completed':'')} onClick={()=>play(m)}><div className="stage-number"><span>0{i+1}</span><span>{completed.includes(m.id)?'✓':'↗'}</span></div><div className="mini-board"><Board stage={m}/></div><small>{['MOVE','PRESSURE','RECORD','COOPERATE','SYNCHRONIZE'][i]}</small><h3>{m.title}</h3><p>{m.description}</p><div className="card-bottom"><span>{m.maxGhosts?`과거 ${m.maxGhosts}명`:'이동 익히기'}</span><span>{completed.includes(m.id)?'다시 플레이':'플레이 →'}</span></div></button>)}</div></section>
 <section className="home-bottom"><div><span className="eyebrow">YOUR NEXT EXPERIMENT</span><h3>새로운 가능성을 설계하세요.</h3><p>발판과 문을 배치하고, 나만의 퍼즐을 직접 풀어보세요.</p></div><button onClick={()=>navigate('studio')}>맵 제작실 열기 ↗</button></section>{myMaps.length>0&&<section><h2>내가 만든 맵</h2><div className="my-maps">{myMaps.map(m=><button key={m.id} onClick={()=>play(m)}><b>{m.title}</b><span>{m.width} × {m.height} · 플레이 →</span></button>)}</div></section>}<div className="save-tools"><label className="text-button">저장 파일 가져오기<input hidden type="file" accept=".json" onChange={e=>{importSave(e.target.files?.[0]);e.target.value='';}}/></label>{!!resume&&<button className="text-button" onClick={()=>download('echoloop-save.json',resume)}>저장 파일 내보내기</button>}<span>진행은 현재 브라우저에 저장됩니다.</span></div></main>}
 {view==='play'&&<main className="play"><div className="play-title"><div><button className="back text-button" onClick={()=>navigate(test?'studio':'home')}>← {test?'제작실로 돌아가기':'실험 목록'}</button><h1>{stage.title}</h1><p>{stage.description}</p></div><span className="pill">{test?'맵 테스트':index>=0?`EXPERIMENT 0${index+1}`:'MY EXPERIMENT'}</span></div><div className="play-layout"><section className="game-panel"><div className="game-stats"><div><span>남은 시간</span><b className={state.tick>250?'warning':''}>{((300-state.tick)/10).toFixed(1)}<small> s</small></b></div><div><span>현재 반복</span><b>0{state.ghosts.length+1}</b></div><div><span>과거 기록</span><b>{state.ghosts.length}<small> / {stage.maxGhosts}</small></b></div><span className={'live-label '+(!paused?'running':'')}>{state.outcome==='WON'?'✓ 탈출 성공':state.outcome==='TIMEOUT'?'시간 종료':paused?'Ⅱ 일시정지':'● 기록 중'}</span></div><div className="timer-track"><div style={{width:`${100-progress}%`}}/></div>
 <div className="game-focus" ref={game} tabIndex={0} role="application" aria-label="게임 조작 영역. 방향키 이동, Enter 기록, Space 일시정지, R 재시작" onKeyDown={down} onKeyUp={up} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))pause();}} onClick={()=>game.current?.focus()}><Board stage={stage} state={state} paths={settings.paths}/>{paused&&state.outcome==='RUNNING'&&<div className="pause-banner"><span>{started?'시간이 잠시 멈췄습니다.':'움직이면 시간이 시작됩니다.'}</span><button onClick={e=>{e.stopPropagation();pause(false);setStarted(true);focus();}}>▷ {started?'계속하기':'시작하기'}</button></div>}</div>
 <div className="legend"><span><i className="dot current"/> 현재의 나</span><span><i className="dot purple"/> 과거의 나</span><span><i className="square yellow"/> 발판</span><span><i className="square green"/> 출구</span></div><div className="game-controls" onPointerDown={e=>e.preventDefault()}><button className="primary" disabled={!state.tick||state.ghosts.length>=stage.maxGhosts||state.outcome==='WON'} onClick={record}>↶ 기록 확정 <kbd>Enter</kbd></button><button disabled={state.outcome!=='RUNNING'} onClick={()=>{pause(!paused);setStarted(true);focus();}}>{paused?'▷ 계속':'Ⅱ 일시정지'} <kbd>Space</kbd></button><button onClick={restart}>↻ 이번 반복 재시작 <kbd>R</kbd></button></div><p className="control-note">기록 확정은 과거를 남깁니다. 재시작은 현재 반복만 지우고 과거를 유지합니다.</p><div className="touch-controls" aria-label="방향 조작">{(['L','U','D','R'] as Move[]).map((dir,i)=><button key={dir} aria-label={['왼쪽','위','아래','오른쪽'][i]} onPointerDown={e=>{e.preventDefault();game.current?.focus();pause(false);setStarted(true);held.current=[dir];queued.current=dir;e.currentTarget.setPointerCapture(e.pointerId);}} onPointerUp={()=>held.current=[]} onPointerCancel={()=>held.current=[]}>{['←','↑','↓','→'][i]}</button>)}</div></section>
 <aside className="play-side"><section className="panel records"><div className="panel-heading"><h3>과거의 나</h3><span>{state.ghosts.length} / {stage.maxGhosts}</span></div>{state.ghosts.length===0?<div className="empty-records"><span>◎</span><b>{stage.maxGhosts?'아직 남겨진 기록이 없어요.':'이번에는 혼자서도 충분해요.'}</b><p>{stage.maxGhosts?'발판 위에서 Enter를 눌러 다음 나에게 도움을 남기세요.':'발판과 출구를 향해 이동해 보세요.'}</p></div>:state.ghosts.map((g,i)=><div className="record" key={g.checksum}><div><span className="ghost-badge" style={{color:colors[i],borderColor:colors[i]}}>{i+1}</span><b>과거 {i+1}</b><button className="icon-button" aria-label={`과거 ${i+1} 삭제`} onClick={()=>{pause();setDeleteIndex(i);}}>×</button></div><div className="record-time">{(g.originalTicks/10).toFixed(1)}초 기록 · 이후 이 위치에서 기다림</div><div className="record-bar"><i style={{width:`${Math.max(g.originalTicks/3,2)}%`,background:colors[i]}}/></div><small>마지막 위치 ({g.cells[300].x}, {g.cells[300].y})</small></div>)}<p className="small muted">과거는 기록된 경로를 그대로 따릅니다.<br/>현재 닫힌 문도 지나갈 수 있어요.</p></section>
 <section className="panel hint"><button className="hint-toggle" onClick={()=>setHint(!hint)}><span>✧ 막혔을 때 힌트</span><span>{hint?'−':'+'}</span></button>{hint&&<p>{stage.hint}</p>}</section><section className="panel shortcuts"><h3>조작 안내</h3><p><span>이동</span><span><kbd>W A S D</kbd> / <kbd>방향키</kbd></span></p><p><span>발판 위에서 대기</span><span>방향키 놓기</span></p><p><span>한 칸의 시간</span><span>0.1초</span></p><p className="muted small">탭을 떠나면 자동으로 멈춥니다.<br/>이동이 안 되면 지도를 클릭해 주세요.</p></section><section className="save-state"><span>◉ {test?'테스트 진행 · 원본 저장 유지':saved}</span>{!test&&<><button className="text-button" onClick={()=>download('echoloop-save.json',saveState(stage,state))}>JSON 내보내기 ↗</button><button disabled={busy} className="text-button" onClick={cloudSave}>{busy?'온라인 저장 중…':'온라인 백업'}</button><button className="text-button" disabled={busy} onClick={cloudRestore}>온라인 백업 복구</button>{cloud&&<small>{cloud}</small>}</>}</section></aside></div>
 {state.outcome!=='RUNNING'&&<div className="modal-backdrop"><section className="modal result" role="dialog" aria-modal="true" aria-labelledby="result-title"><span className="result-symbol">{state.outcome==='WON'?'✦':'↶'}</span><span className="eyebrow">{state.outcome==='WON'?'EXPERIMENT COMPLETE':'END OF LOOP'}</span><h2 id="result-title">{state.outcome==='WON'?'우리는, 해냈습니다.':'30초가 지났습니다.'}</h2><p>{state.outcome==='WON'?`${state.ghosts.length}명의 과거와 ${(state.tick/10).toFixed(1)}초 만에 출구에 도착했습니다.`:'이 행동을 과거로 남기거나 이번 반복을 다시 시작하세요.'}</p>{state.outcome==='WON'&&<p className="verification">✓ 입력 기록을 다시 실행해 해답을 확인했습니다.</p>}<div className="modal-actions">{state.outcome==='WON'?<><button className="primary" onClick={()=>test?navigate('studio'):index>=0&&index<4?play(stages[index+1]):navigate('home')}>{test?'해답과 함께 제작실로':index>=0&&index<4?'다음 실험 →':'실험 목록으로'}</button><button onClick={()=>{pause();assign(initial(stage));setStarted(false);focus();}}>처음부터 다시</button></>:<><button className="primary" disabled={state.ghosts.length>=stage.maxGhosts} onClick={record}>기록 확정</button><button onClick={restart}>이번 반복 재시작</button><button onClick={()=>{pause();assign(initial(stage));setStarted(false);focus();}}>모든 기록 지우고 시작</button></>}</div>{state.outcome==='TIMEOUT'&&state.ghosts.length>=stage.maxGhosts&&<p className="muted">과거 기록 한도를 모두 사용했습니다.</p>}</section></div>}</main>}
 {view==='studio'&&<Studio onTest={m=>play(m,true)} result={studioResult} notify={notify} onConsumeResult={()=>setStudioResult(null)}/>}
 <footer><span>EchoLoop <b>·</b> A little experiment with time.</span><span>개인 플레이 베타 · v0.1</span></footer>
 {toast&&<div className="toast" role="status">{toast}<button aria-label="알림 닫기" onClick={()=>setToast('')}>×</button></div>}
 {deleteIndex!==null&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="delete-title"><h2 id="delete-title">과거 {deleteIndex+1}부터 지울까요?</h2><p>과거 {deleteIndex+1}~{state.ghosts.length}와 현재 미확정 반복이 삭제됩니다. 앞선 기록은 유지됩니다.</p><div className="modal-actions"><button onClick={()=>setDeleteIndex(null)}>취소</button><button className="danger" onClick={()=>{assign(initial(stage,state.ghosts.slice(0,deleteIndex)));setDeleteIndex(null);setStarted(false);focus();}}>기록 삭제</button></div></section></div>}
 {settingsOpen&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="settings-title"><h2 id="settings-title">편안한 실험을 위해</h2>{([['paths','과거 이동 경로 표시'],['motion','부드러운 움직임'],['large','글자 크게 보기'],['sound','기록·완료 효과음']] as [keyof Settings,string][]).map(([k,label])=><label className="setting-row" key={k}>{label}<input type="checkbox" checked={settings[k]} onChange={e=>{const next={...settings,[k]:e.target.checked};setSettings(next);write('settings',next).catch(()=>notify('설정 저장 실패'));}}/></label>)}<button className="primary" onClick={()=>{setSettingsOpen(false);focus();}}>완료</button></section></div>}
 {help&&<div className="modal-backdrop"><section className="modal help" role="dialog" aria-modal="true" aria-labelledby="help-title"><span className="eyebrow">HOW TO ECHO</span><h2 id="help-title">다음 나를 위한 30초</h2><ol><li><b>먼저, 길을 살펴보세요.</b><p>발판 A와 연결된 문을 찾으세요. 시작 전에는 시간이 흐르지 않습니다.</p></li><li><b>발판 위에 나를 남기세요.</b><p>발판까지 이동한 뒤 Enter. 과거의 나는 같은 길을 걷고 마지막 자리에서 기다립니다.</p></li><li><b>열린 문 너머로 가세요.</b><p>다음 나는 과거의 도움을 받아 출구로 갑니다. AND 문은 연결된 발판을 모두 밟아야 열립니다.</p></li></ol><p className="muted">과거는 현재 닫힌 문도 통과합니다. 기록은 바뀌지 않으니까요. 기록을 지우면 그 이후의 기록도 함께 지워집니다.</p><button className="primary" onClick={()=>{setHelp(false);focus();}}>알겠어요</button></section></div>}
 </>;
}
createRoot(document.getElementById('root')!).render(<App/>);
