import {fromRows} from './stage-factory.ts';
import type {Stage,Move,Cell} from './engine.ts';
export type NewPuzzle={stage:Stage;records:(Cell|Move[])[];difficulty:number;idea:string};
const puzzles:NewPuzzle[]=[];
const wait=(n:number):Move[]=>Array<Move>(n).fill('.');
function add(m:Stage,records:(Cell|Move[])[],difficulty:number,idea:string){puzzles.push({stage:m,records,difficulty,idea});}
const room=['###########','#....#....#','#....#....#','#....a..G.#','#S...#....#','#....#....#','###########'];
function box(id:string,title:string){const m=fromRows(id,title,'현재만 상자를 밀 수 있습니다. 상자는 일반 무게 발판을 계속 누릅니다.','상자 아래로 돌아가 위로 밀어 A에 놓으세요. 과거는 상자를 통과하지만 밀지는 않습니다.',room,0);m.plates=[{id:'a',x:3,y:2}];m.doors[0].plateIds=['a'];m.crates=[{x:3,y:3}];return m;}
let m=box('crate-01','남겨 둔 무게');add(m,[],12,'상자를 발판에 두고 현재가 떠나는 입문');
m=fromRows('crate-02','두 개의 짐','두 상자가 서로 다른 발판을 맡아야 합니다.','각 상자 아래로 돌아가 A와 B로 밀어 올리세요. 문은 두 무게가 모두 놓여야 열립니다.',['############','#.....#....#','#.A.B.#....#','#.....a..G.#','#S....#....#','#.....#....#','############'],0);m.crates=[{x:2,y:3},{x:4,y:3}];m.doors[0].mode='AND';m.doors[0].plateIds=['plate-a','plate-b'];add(m,[],22,'밀기 순서와 두 발판의 AND 조건');
m=box('crate-03','상자와 과거의 분업');m.maxGhosts=1;m.plates.push({id:'b',x:1,y:1,kind:'echo'});m.doors[0].mode='AND';m.doors[0].plateIds=['a','b'];m.description='상자는 A, 과거는 B. 서로 다른 존재에게 역할을 맡기세요.';m.hint='B에 기록을 남기고 현재는 상자를 A로 밀어 올립니다. 상자로 과거 전용 B를 누를 수는 없습니다.';add(m,[m.plates[1]],32,'상자로 대체할 수 없는 과거 전용 발판');
function crumble(id:string,title:string){const n=fromRows(id,title,'분홍 균열은 현재가 떠나면 무너집니다. 과거는 구멍을 통과합니다.','조각 방에서 되돌아오면 다리가 끊깁니다. 오른쪽 길을 따라 한 바퀴 돌아 나오세요.',['##########','#..#.....#','#S.......#','###.##...#','#...##.G.#','#........#','##########'],0);n.shards=[{x:4,y:2}];n.fragile=[{x:3,y:2}];return n;}
m=crumble('crumble-01','돌아갈 수 없는 발자국');m.tiles[2*m.width+5]=1;m.tiles[1*m.width+4]=1;m.tiles[3*m.width+4]=0;m.tiles[4*m.width+4]=0;add(m,[],15,'조각을 얻은 뒤 같은 다리로 돌아갈 수 없음');
m=fromRows('crumble-02','무너져도 남는 길','현재의 귀환 길은 끊겨도, 기록은 그대로 재생됩니다.','첫 나는 균열을 건너 A에서 기록합니다. 다음 현재는 같은 길을 새로 건너고 과거가 연 문으로 나갑니다.',['###########','#....#....#','#..A.#....#','#S...a..G.#','#....#....#','#....#....#','###########'],1);m.plates[0].kind='echo';m.fragile=[{x:2,y:3},{x:3,y:3},{x:4,y:3}];m.tiles[2*m.width+2]=1;m.tiles[4*m.width+2]=1;add(m,[m.plates[0]],25,'반복마다 바닥 초기화·과거는 구멍을 무시');
m=crumble('crumble-03','한 번뿐인 순환');m.shards=[{x:4,y:2},{x:2,y:5}];m.fragile=[{x:3,y:2},{x:3,y:3},{x:6,y:4}];m.tiles[2*m.width+5]=1;m.tiles[1*m.width+4]=1;m.tiles[3*m.width+4]=0;m.tiles[4*m.width+4]=0;add(m,[],34,'두 조각과 세 붕괴 지점의 방문 순서');
function reverse(id:string,title:string){const n=fromRows(id,title,'이 방의 과거는 기록 끝에서 출발해 거꾸로 움직입니다.','A로 이동한 뒤 약 2초 기다리고 기록하세요. 다음 반복은 A에 서 있는 과거로 시작합니다. 과거가 떠나기 전에 문을 건넙니다.',['###########','#.A.#.....#','#...#.....#','#S..a..G..#','#...#.....#','#...#.....#','###########'],1);n.echoMode='reverse';n.plates[0].kind='echo';return n;}
m=reverse('reverse-01','끝에서 시작하는 나');add(m,[['U','U','R',...wait(20)]],18,'역재생의 시작 위치와 대기 시간');
m=fromRows('reverse-02','거꾸로 놓인 순서','과거는 B에서 A로 돌아갑니다. 현재의 문도 B, A 순서입니다.','A에 올라 약 1.5초 기다린 뒤 B에서 약 2초 기다려 기록하세요. 현재는 B의 문을 먼저, A의 문을 나중에 건넙니다.',['############','#..A.B#....#','#.....#.#G.#','#S....b.a..#','#.....#.#..#','#.....#.#..#','############'],1);m.echoMode='reverse';m.plates.forEach(p=>p.kind='echo');add(m,[['U','U','R','R',...wait(15),'R','R',...wait(20)]],38,'역재생으로 문 신호의 순서가 뒤집힘');
m=reverse('reverse-03','역행하는 두 목소리');m.maxGhosts=2;m.plates[0].kind='resonance';m.plates[0].minActors=3;m.hint='두 기록 모두 A로 가 약 2초 머문 뒤 확정합니다. 마지막 현재도 A에 합류한 다음 문으로 향하세요.';m.description='두 과거와 현재가 A에 함께 있어야 열립니다. 역재생이 합류 시간을 바꿉니다.';m.tiles[3*m.width+4]=1;m.doors[0].x=3;m.doors[0].y=1;m.tiles[1*m.width+4]=0;add(m,[['U','U','R',...wait(20)],['U','U','R',...wait(20)]],48,'세 명 공명과 역재생의 짧은 합류 창');
// A fragile neck makes the shard room a genuine one-way pocket. Jump is its only exit.
function jump(id:string,title:string){const n=fromRows(id,title,'조각 방의 다리가 무너지면 선택한 과거에게 도약하세요.','첫 기록은 오른쪽 방의 A에 남깁니다. 다음 현재는 왼쪽 위 조각을 얻고 J 또는 잔상 도약 버튼으로 과거에게 이동합니다.',['############','#.#####....#','#...###....#','###.##A....#','#.S....a.G.#','#....##....#','############'],1);n.plates[0].kind='echo';n.echoJump=true;n.shards=[{x:2,y:1}];n.fragile=[{x:3,y:2}];n.tiles[1*n.width+2]=0;n.tiles[3*n.width+6]=0;for(let y=1;y<6;y++)if(y!==4)n.tiles[y*n.width+7]=1;return n;}
m=jump('jump-01','끊긴 다리의 저편');add(m,[m.plates[0]],28,'붕괴된 막다른 조각 방에서 단 한 번 도약');
m=jump('jump-02','두 번째 나를 골라');m.maxGhosts=2;m.plates.push({id:'b',x:1,y:5,kind:'echo'});m.doors.push({id:'entry',x:5,y:4,mode:'OR',plateIds:['b']});m.tiles[3*m.width+5]=1;m.tiles[5*m.width+5]=1;m.hint='과거 1은 왼쪽 아래 B, 과거 2는 열린 입구를 지나 A에 남깁니다. 마지막 현재는 조각을 얻고 과거 2를 선택해 도약합니다.';add(m,[m.plates[1],m.plates[0]],44,'입구를 맡는 기록과 도약 목적지 기록의 분리');
m=jump('jump-03','사라지기 전의 착지');m.echoMode='reverse';m.hint='오른쪽 A에서 약 3초 기다린 뒤 기록합니다. 현재는 조각 방으로 가고, 역행하는 과거가 돌아오기 전에 도약하세요.';add(m,[['R','R','R','R','U',...wait(30)]],42,'역재생의 유한한 원격 착지 창');
function stasis(id:string,title:string){const n=fromRows(id,title,'청록 정지 장치 위에 서 있으면 과거 1만 멈춥니다. 문 박자는 계속 흐릅니다.','A로 가 약 0.5초 기다린 뒤 내려오는 행동까지 기록하세요. 현재는 과거가 A에 도착했을 때 정지 장치를 밟고, 문 박자를 기다립니다.',['###########','#.A.#.....#','#...#.....#','#S..a..G..#','#...#.....#','#...#.....#','###########'],1);n.plates[0].kind='echo';n.stasis=[{x:3,y:3,ghost:1}];n.doors[0].pulse={period:30,openTicks:5,offset:12};return n;}
m=stasis('stasis-01','한 사람의 시간만');add(m,[['U','U','R',...wait(5),'D']],30,'짧은 점유를 정지 장치로 박동까지 연장');
m=stasis('stasis-02','서로 다른 시계');m.maxGhosts=2;m.plates.push({id:'b',x:2,y:5,kind:'echo'});m.doors[0].mode='AND';m.doors[0].plateIds=['plate-a','b'];m.hint='과거 1은 A에 잠깐 머물고 떠납니다. 과거 2는 약 2초 기다린 뒤 B에 남깁니다. 현재는 정지 장치로 과거 1을 붙잡으며 과거 2의 도착과 문 박자를 기다립니다.';add(m,[['U','U','R',...wait(5),'D'],[...wait(20),'D','D','R']],50,'1만 정지시키고 2와 세계 시계는 진행');
m=stasis('stasis-03','붙잡은 역행');m.echoMode='reverse';m.hint='A에서 약 0.5초 머문 뒤 기록합니다. 과거는 A에서 출발합니다. 현재는 정지 장치로 과거의 역행을 멈춘 채 문 박자를 기다립니다.';add(m,[['U','U','R',...wait(5)]],46,'역재생 정지와 출발 위치의 차이');
m=box('confluence-01','상자 뒤로 끊기는 다리');m.fragile=[{x:2,y:4},{x:3,y:4},{x:4,y:3}];m.shards=[{x:1,y:1}];m.hint='왼쪽 위 조각을 먼저 챙기세요. 상자를 A로 밀고, 무너진 길을 피해 위쪽으로 돌아 문에 접근합니다.';add(m,[],36,'상자 배치와 조각 회수·붕괴 귀환 순서');
m=box('confluence-02','무게와 멈춘 역행');m.maxGhosts=1;m.echoMode='reverse';m.plates.push({id:'b',x:1,y:1,kind:'echo'});m.doors[0].mode='AND';m.doors[0].plateIds=['a','b'];m.doors[0].pulse={period:40,openTicks:5,offset:12};m.stasis=[{x:4,y:3,ghost:1}];m.hint='B에서 약 1.5초 머물고 기록하세요. 현재는 상자를 A에 올린 뒤 정지 장치로 B의 과거를 붙잡아 문 박자를 기다립니다.';add(m,[['U','U','U',...wait(15)]],58,'상자·역재생·정지·박동의 네 조건');
m=jump('confluence-03','이어받는 정지 신호');m.maxGhosts=2;m.plates.push({id:'b',x:1,y:5,kind:'echo'});m.doors.push({id:'entry',x:5,y:4,mode:'OR',plateIds:['b'],pulse:{period:30,openTicks:5,offset:12}});m.tiles[3*m.width+5]=1;m.tiles[5*m.width+5]=1;m.stasis=[{x:4,y:4,ghost:1}];m.hint='과거 1은 B에 약 0.8초 머물고 떠납니다. 과거 2는 입구 앞 정지 장치에서 B를 붙잡아 박동 문을 건넌 뒤 A에 남깁니다. 마지막 현재는 조각 방에서 과거 2에게 도약합니다.';add(m,[['D','L',...wait(8),'R'],m.plates[0]],66,'정지로 만든 두 번째 기록에 도약해 붕괴 방 탈출');
// The crate opens entry, the remote echo opens the exit, and the shard pocket requires a jump.
function finale(id:string,title:string){const n=jump(id,title);n.echoMode='reverse';n.plates.push({id:'weight',x:4,y:2});n.crates=[{x:4,y:3}];n.tiles[2*n.width+4]=0;n.tiles[3*n.width+4]=0;n.doors.push({id:'entry',x:5,y:4,mode:'OR',plateIds:['weight']});n.tiles[3*n.width+5]=1;n.tiles[5*n.width+5]=1;n.doors[0].mode='AND';n.doors[0].plateIds=['plate-a','weight'];n.hint='상자를 왼쪽 무게 발판에 올리고 오른쪽 과거 전용 발판에서 약 3초 기다려 기록하세요. 다음 현재도 상자를 다시 올려 입구와 출구를 열고, 조각 방에 들어갔다가 과거에게 도약합니다.';return n;}
m=finale('confluence-04','무너진 인과를 건너');m.description='상자, 붕괴 바닥, 역재생, 도약. 현재와 과거의 임무가 네 갈래로 나뉩니다.';add(m,[['R','R','U','D','R','R','U',...wait(30)]],74,'매 반복 상자를 재배치하고 역행 도약 창에 맞춰 조각 회수');
m=finale('confluence-05','다섯 시간의 결절');m.stasis=[{x:2,y:2,ghost:1}];m.doors[0].pulse={period:80,openTicks:6,offset:35};m.hint='상자를 무게 발판에 올리고 오른쪽 발판에서 약 1.8초 머물러 기록하세요. 현재도 상자를 올리고 조각을 챙긴 뒤, 조각 방의 정지 장치에서 역행을 붙잡아 기다립니다. 첫 박자가 지나간 뒤 약 4.4초에 도약해 다음 열린 문으로 나가세요.';m.description='상자·붕괴·역재생·도약·정지와 박동을 모두 묶는 마지막 실험입니다.';add(m,[['R','R','U','D','R','R','U',...wait(18)]],100,'다섯 새 기믹을 모두 써서 불가능한 귀환과 두 시계를 연결');
export const newMechanicPuzzles=puzzles;
