import {useEffect,useState} from 'react';
import {Board} from './Board.tsx';
import {type Stage,type Cell,validateStage,hash,equal,type Solution,verifySolution} from './engine.ts';
import {blankStage,stages} from './stages.ts';
import {read,write,download,parseFile} from './storage.ts';
type Tool='floor'|'wall'|'spawn'|'goal'|'plate'|'echo'|'present'|'resonance'|'toggle'|'portal'|'arrow'|'door'|'select';
export function Studio({onTest,result,notify,onConsumeResult}:{onTest:(m:Stage)=>void;result:{stage:Stage;solution:Solution}|null;notify:(s:string)=>void;onConsumeResult:()=>void}){
 const [m,setMap]=useState<Stage>(()=>blankStage()),[past,setPast]=useState<Stage[]>([]),[future,setFuture]=useState<Stage[]>([]),[tool,setTool]=useState<Tool>('wall'),[sel,setSel]=useState<Cell>(),[ready,setReady]=useState(false),[size,setSize]=useState([13,9]);
 const [portalStart,setPortalStart]=useState<Cell>();
 const [verified,setVerified]=useState<{checksum:string;solution:Solution}|null>(null),[zoom,setZoom]=useState(1);
 useEffect(()=>{if(result){setReady(true);return;}read<Stage>('draft').then(v=>{if(v&&!validateStage(v).some(e=>e.includes('타일')))setMap(v);}).catch(()=>notify('초안을 불러오지 못했습니다.')).finally(()=>setReady(true));},[]);
 useEffect(()=>{if(!ready)return;const timer=setTimeout(()=>write('draft',m).catch(()=>notify('초안 저장 실패. JSON으로 내보내세요.')),500);return()=>clearTimeout(timer);},[m,ready]);
 useEffect(()=>{if(result){try{verifySolution(result.stage,result.solution);setMap(result.stage);setVerified({checksum:hash(result.stage),solution:result.solution});onConsumeResult();}catch{notify('해답 검증에 실패했습니다.');}}},[result]);
 const edit=(next:Stage)=>{setPast(v=>[...v.slice(-99),structuredClone(m)]);setFuture([]);setMap(next);};
 const errors=validateStage(m),door=m.doors.find(d=>sel&&equal(d,sel)),checked=verified?.checksum===hash(m),plate=m.plates.find(p=>sel&&equal(p,sel)),arrow=m.arrows?.find(p=>sel&&equal(p,sel)),portal=m.portals?.find(p=>sel&&(equal(p.a,sel)||equal(p.b,sel)));
 function cell(c:Cell){setSel(c);if(tool==='select')return;if(c.x===0||c.y===0||c.x===m.width-1||c.y===m.height-1)return notify('가장자리는 벽으로 고정됩니다.');
  if((equal(m.spawn,c)&&tool!=='spawn')||(equal(m.goal,c)&&tool!=='goal'))return notify('출발·출구는 해당 도구로 다른 칸에 옮겨주세요.');
  if(tool==='portal'&&!portalStart){if(m.plates.some(p=>equal(p,c))||m.doors.some(d=>equal(d,c))||m.portals?.some(p=>equal(p.a,c)||equal(p.b,c))||m.arrows?.some(a=>equal(a,c)))return notify('비어 있는 칸을 첫 포털로 선택하세요.');setPortalStart(c);return notify('첫 포털 선택 완료. 연결할 두 번째 칸을 클릭하세요.');}
  if(tool==='portal'&&portalStart&&equal(portalStart,c))return notify('서로 다른 두 칸을 선택하세요.');
  const n=structuredClone(m);if(n.portals)n.portals=n.portals.filter(p=>!equal(p.a,c)&&!equal(p.b,c));if(n.arrows)n.arrows=n.arrows.filter(a=>!equal(a,c));n.plates=n.plates.filter(p=>!equal(p,c));n.doors=n.doors.filter(d=>!equal(d,c));n.tiles[c.y*n.width+c.x]=tool==='wall'?1:0;
  if(tool==='spawn')n.spawn=c;if(tool==='goal')n.goal=c;
  if(['plate','echo','present','resonance','toggle'].includes(tool)){if(n.plates.length>=16)return notify('발판은 최대 16개입니다.');n.plates.push({...c,id:'p-'+crypto.randomUUID().slice(0,8),kind:tool==='resonance'?'resonance':tool==='toggle'?'toggle':tool==='echo'?'echo':tool==='present'?'present':'weight'});}
  if(tool==='portal'&&portalStart){if((n.portals?.length??0)>=8)return notify('포털은 최대 8쌍입니다.');n.tiles[portalStart.y*n.width+portalStart.x]=0;n.portals=[...(n.portals??[]),{id:'fold-'+crypto.randomUUID().slice(0,8),a:portalStart,b:c}];setPortalStart(undefined);}
  if(tool==='arrow')n.arrows=[...(n.arrows??[]),{...c,direction:'R'}];
  if(tool==='door'){if(n.doors.length>=16)return notify('문은 최대 16개입니다.');n.doors.push({...c,id:'d-'+crypto.randomUUID().slice(0,8),mode:'OR',plateIds:[]});setTool('select');}
  edit(n);
 }
 function exportMap(){if(errors.length)return notify('구조 오류를 먼저 해결하세요.');download('echoloop-map.json',m);}
 async function importMap(file?:File){if(!file)return;try{const v=await parseFile(file,131072) as Stage;const e=validateStage(v);if(e.length)throw new Error(e.join('\n'));edit(v);notify('맵을 가져왔습니다.');}catch(e){notify((e as Error).message);}}
 async function saveLocal(){if(errors.length)return notify('구조 오류를 먼저 해결하세요.');try{const maps=await read<Stage[]>('maps')??[];const next=[m,...maps.filter(v=>v.id!==m.id)].slice(0,30);await write('maps',next);notify('내 맵 목록에 저장했습니다.');}catch{notify('저장하지 못했습니다. JSON 내보내기를 사용하세요.');}}
 return <main className="studio"><div className="section-heading"><div><span className="eyebrow">MAP STUDIO</span><h1>나만의 시간 실험</h1><p>길을 만들고, 발판과 문을 연결하세요.</p></div><button className="primary" disabled={!!errors.length} onClick={()=>{write('draft',m).catch(()=>{});onTest(structuredClone(m));}}>▷ 테스트 플레이</button></div>
 <div className="studio-layout"><aside className="panel tools"><h3>타일 도구</h3><div className="tool-grid">{([['select','⌖','선택'],['floor','▫','바닥'],['wall','▦','벽'],['spawn','S','출발'],['goal','↗','출구'],['plate','A','공통 발판'],['echo','◇','잔상 발판'],['present','✦','실체 발판'],['resonance','2×','공명 발판'],['toggle','↺','기억 스위치'],['portal','◎','포털 쌍'],['arrow','»','방향 통로'],['door','▥','문']] as [Tool,string,string][]).map(([id,icon,label])=><button key={id} className={tool===id?'active':''} onClick={()=>{setTool(id);setPortalStart(undefined);}}><b>{icon}</b>{label}</button>)}</div><p className="muted small">문은 발판을 연결하세요. 포털은 두 칸을 차례로 클릭합니다. 방향 통로와 박동 문은 선택 후 속성을 바꿀 수 있어요.</p>{portalStart&&<button onClick={()=>setPortalStart(undefined)}>포털 연결 취소</button>}<div className="split"><button disabled={!past.length} onClick={()=>{setFuture(v=>[m,...v]);setMap(past.at(-1)!);setPast(v=>v.slice(0,-1));}}>↶ 실행 취소</button><button disabled={!future.length} onClick={()=>{setPast(v=>[...v,m]);setMap(future[0]);setFuture(v=>v.slice(1));}}>↷ 다시 실행</button></div><h3>맵 크기</h3><div className="split"><label>가로<input type="number" min="8" max="32" value={size[0]} onChange={e=>setSize([+e.target.value,size[1]])}/></label><label>세로<input type="number" min="6" max="24" value={size[1]} onChange={e=>setSize([size[0],+e.target.value])}/></label></div><button onClick={()=>{if(!Number.isInteger(size[0])||size[0]<8||size[0]>32||!Number.isInteger(size[1])||size[1]<6||size[1]>24)return notify('가로 8~32, 세로 6~24로 입력하세요.');if(confirm('현재 맵을 빈 맵으로 교체할까요? 실행 취소로 되돌릴 수 있습니다.'))edit(blankStage(...size as [number,number]));}}>빈 맵으로 새로 만들기</button><button onClick={()=>{if(confirm('대표 퍼즐을 복사해 편집할까요?'))edit({...structuredClone(stages[3]),id:'local-'+crypto.randomUUID(),title:'두 개의 문 — 내 버전'});}}>대표 퍼즐 불러오기</button></aside>
 <section className="panel studio-board"><div className="board-toolbar"><span>{m.width} × {m.height} 격자</span><label>확대 <input type="range" min="1" max="2" step=".1" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label></div><div className="board-scroll"><div style={{width:`${zoom*100}%`}}><Board stage={m} connections onCell={cell} selected={sel}/></div></div><div className="studio-status">{sel?`선택 좌표 (${sel.x}, ${sel.y})`:'격자를 클릭해 편집하세요.'}<span>{checked?'✓ 해답 재생 확인됨':'해답 미검증'}</span></div></section>
 <aside className="panel properties"><h3>맵 정보</h3><label>이름<input maxLength={80} value={m.title} onChange={e=>edit({...m,title:e.target.value})}/></label><label>설명<textarea maxLength={1000} value={m.description} onChange={e=>edit({...m,description:e.target.value})}/></label><label>힌트<textarea maxLength={1000} value={m.hint} onChange={e=>edit({...m,hint:e.target.value})}/></label><label>과거 기록 한도<select value={m.maxGhosts} onChange={e=>edit({...m,maxGhosts:+e.target.value})}>{[0,1,2,3].map(n=><option key={n}>{n}</option>)}</select></label>
 {door&&<div className="door-editor"><h3>선택한 문 연결</h3><label className="check"><input type="checkbox" checked={!!door.inverted} onChange={e=>edit({...m,doors:m.doors.map(d=>d.id===door.id?{...d,inverted:e.target.checked}:d)})}/>반전 · 발판 조건이 꺼지면 열림</label><label className="check"><input type="checkbox" checked={!!door.pulse} onChange={e=>edit({...m,doors:m.doors.map(d=>d.id===door.id?{...d,pulse:e.target.checked?{period:20,openTicks:8,offset:0}:undefined}:d)})}/>주기적으로 열리는 박동 문</label>{door.pulse&&<div className="split"><label>주기(초)<input type="number" min="0.4" max="10" step="0.1" value={door.pulse.period/10} onChange={e=>edit({...m,doors:m.doors.map(d=>d.id===door.id?{...d,pulse:{...d.pulse!,period:Math.round(+e.target.value*10)}}:d)})}/></label><label>열림(초)<input type="number" min="0.1" max="9.9" step="0.1" value={door.pulse.openTicks/10} onChange={e=>edit({...m,doors:m.doors.map(d=>d.id===door.id?{...d,pulse:{...d.pulse!,openTicks:Math.round(+e.target.value*10)}}:d)})}/></label></div>}<select aria-label="문 조건" value={door.mode} onChange={e=>edit({...m,doors:m.doors.map(d=>d.id===door.id?{...d,mode:e.target.value as 'AND'|'OR'}:d)})}><option value="OR">OR · 하나라도 밟으면</option><option value="AND">AND · 모두 밟으면</option></select>{m.plates.map((p,i)=><label className="check" key={p.id}><input type="checkbox" checked={door.plateIds.includes(p.id)} onChange={e=>edit({...m,doors:m.doors.map(d=>d.id===door.id?{...d,plateIds:e.target.checked?[...d.plateIds,p.id]:d.plateIds.filter(id=>id!==p.id)}:d)})}/>발판 {String.fromCharCode(65+i)} ({p.x}, {p.y})</label>)}</div>}
 {plate&&<div className="door-editor"><h3>발판이 감지하는 존재</h3><select aria-label="발판 종류" value={plate.kind??'weight'} onChange={e=>edit({...m,plates:m.plates.map(p=>p.id===plate.id?{...p,kind:e.target.value as 'weight'|'echo'|'present'|'resonance'|'toggle',minActors:undefined}:p)})}><option value="weight">공통 · 모두 감지</option><option value="echo">잔상 · 과거만 감지</option><option value="present">실체 · 현재만 감지</option><option value="resonance">공명 · 함께 서야 켜짐</option><option value="toggle">기억 · 다시 밟으면 반전</option></select>{plate.kind==='resonance'&&<label>필요한 인원<select aria-label="공명 인원" value={plate.minActors??2} onChange={e=>edit({...m,plates:m.plates.map(p=>p.id===plate.id?{...p,minActors:+e.target.value as 2|3}:p)})}><option value="2">2명</option><option value="3">3명</option></select></label>}</div>}
 {arrow&&<div className="door-editor"><h3>진입 가능한 방향</h3><select aria-label="통로 방향" value={arrow.direction} onChange={e=>edit({...m,arrows:m.arrows?.map(a=>equal(a,arrow)?{...a,direction:e.target.value as 'U'|'D'|'L'|'R'}:a)})}><option value="R">→ 오른쪽으로 진입</option><option value="L">← 왼쪽으로 진입</option><option value="U">↑ 위쪽으로 진입</option><option value="D">↓ 아래쪽으로 진입</option></select></div>}
 {portal&&<div className="door-editor"><h3>연결된 포털</h3><p className="small">({portal.a.x}, {portal.a.y}) ↔ ({portal.b.x}, {portal.b.y})</p><button onClick={()=>edit({...m,portals:m.portals?.filter(p=>p.id!==portal.id)})}>이 포털 쌍 지우기</button></div>}
 <div className={'validation '+(errors.length?'invalid':'valid')}><b>{errors.length?`구조 오류 ${errors.length}개`:'✓ 맵 구조 정상'}</b>{errors.slice(0,5).map(e=><p key={e}>{e}</p>)}{!errors.length&&<p>{checked?'실제 플레이 해답을 다시 실행해 출구 도달을 확인했습니다.':'구조 검사만 완료했습니다. 테스트를 클리어하면 해답을 검증합니다.'}</p>}</div>
 <button className="primary" onClick={saveLocal}>내 맵에 저장</button><div className="split"><button onClick={exportMap}>맵 내보내기</button><label className="button">가져오기<input type="file" accept=".json" hidden onChange={e=>{importMap(e.target.files?.[0]);e.target.value='';}}/></label></div>{checked&&<button onClick={()=>download('echoloop-solution.json',{stage:m,solution:verified!.solution})}>검증된 해답 내보내기</button>}</aside></div></main>;
}
